### ISSUE TITLE
Connection brokes on messages.setActivity

### ISSUE THREAD

**Issue by tomyumm-ge** [Suenweek/async-vk-bot#1]
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/chron/PycharmProjects/canadatalks/bot.py", line 53, in <module>
    trio.run(main)
  File "C:\Users\chron\PycharmProjects\canadatalks\venv\lib\site-packages\trio\_core\_run.py", line 1337, in run
    raise runner.main_task_outcome.error
  File "C:/Users/chron/PycharmProjects/canadatalks/bot.py", line 49, in main
    nursery.start_soon(prfmsg, bot)
  File "C:\Users\chron\PycharmProjects\canadatalks\venv\lib\site-packages\trio\_core\_run.py", line 398, in __aexit__
    raise combined_error_from_nursery
  File "C:/Users/chron/PycharmProjects/canadatalks/bot.py", line 33, in prfmsg
    type='typing'
  File "C:\Users\chron\PycharmProjects\canadatalks\venv\lib\site-packages\async_vk_api\api.py", line 75, in __call__
    return await self.group.api(self.full_name, **params)
  File "C:\Users\chron\PycharmProjects\canadatalks\venv\lib\site-packages\async_vk_api\api.py", line 40, in __call__
    params=params
  File "C:\Users\chron\PycharmProjects\canadatalks\venv\lib\site-packages\asks\sessions.py", line 211, in request
    await self._handle_exception(e, sock)
  File "C:\Users\chron\PycharmProjects\canadatalks\venv\lib\site-packages\asks\sessions.py", line 249, in _handle_exception
    raise BadHttpResponse('Invalid HTTP response from server.') from e
asks.errors.BadHttpResponse: Invalid HTTP response from server.

Process finished with exit code 1```

Perform message function:
```async def prfmsg(bot):
    async with bot.sub(new_message) as events:
        async for event in events:
            await bot.api.messages.setActivity(
                peer_id=event['object']['peer_id'],
                type='typing'
            )
            msg = await perform(event['object']['peer_id'], event['object']['text'])
            await bot.api.messages.send(
                peer_id=event['object']['peer_id'],
                message=msg
            )```
Very random cases after ~3 min of running

**Comment by Suenweek** [comment]
Hi, thanks for checking out the project! :)

I had this error previously. It seems to be related to `h11` state machine event triggered state transition.

```
h11._util.RemoteProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
```

I doubt that VK servers misbehave. Probably it is just me missing something obvious. Might be also a bug in `asks` http client.

Unfortunately I was unable to catch the error with Wireshark to see what's going on under the hood. You seem to get it frequently, so it would be cool if you could also give it a try and share your thoughts if you find something :)

**Comment by Chronosms** [comment]
@Suenweek, i'll test it today. I'll be back with results. Thank you for your great work.

**Comment by Chronosms** [comment]
Seems to be going well... It doesn't have any issues now. If i'll have any other issues - i'll write them.

This issue is solved. **Bug was fixed**. Thank you for it.

**Comment by Suenweek** [comment]
Thanks for feedback :) I will close the issue.
